### ISSUE TITLE
 Can you add a small example of soc integration?

### ISSUE THREAD

**Issue by feiger313** [WilsonChen003/HDLGen#10]
Hi WilsonCHen,
Can you add a small example of soc integration? Or make a video For those who are not familiar with top-level integration in this way, it is difficult to know how to use EMBEDDED FUNCTION

**Comment by WilsonChen003** [comment]
En, this is doable , but the most difficult thing is to have full code of a SOC, which need a list of necessary IPs like CPU, Bus-Matrix, Peripheral IPs, and other multi-media IPs, in RTL a/o IPXACT format.
And source or suggestion is really helpful.
Regards,
Wilson
